apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce-svc
  namespace: default
spec:
  ports:
  - name: gitlab-ce-22
    port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 32122
  - name: gitlab-ce-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32180
  - name: gitlab-ce-443
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 32543
  selector:
    name: gitlab-ce
  sessionAffinity: None
  type: NodePort
