apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gitlab-runner
#  namespace: YOUR_GITLAB_BUILD_NAMESPACE
  labels:
    app: gitlab-runner
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  serviceName: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - gitlab-runner
      volumes:
      - name: gitlab-runner-scripts
        projected:
          sources:
          - configMap:
              name: gitlab-runner-scripts
              items:
              - key: run.sh
                path: run.sh
                mode: 0755
#      serviceAccountName: gitlab-ci
      serviceAccountName: default
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 999
#        supplementalGroups: [999]
      containers:
      - image: gitlab/gitlab-runner:alpine-v11.1.0
        name: gitlab-runner
        command:
        - /scripts/run.sh
        envFrom:
        - configMapRef:
            name: gitlab-runner-cm
        - secretRef:
            name: gitlab-runner-token
        env:
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9100
          name: http-metrics
          protocol: TCP
        volumeMounts:
        - name: gitlab-runner-scripts
          mountPath: "/scripts"
          readOnly: true
      restartPolicy: Always
