apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce-svc
  namespace: default
spec:
  ports:
  - name: gitlab-ce-22
    protocol: TCP
    port: 32122     # svc
    targetPort: 22  # pod
    nodePort: 32122 # node
  - name: gitlab-ce-80
    protocol: TCP
    port: 32180
    targetPort: 32180
    nodePort: 32180
  - name: gitlab-ce-443
    protocol: TCP
    port: 32543
    targetPort: 443
    nodePort: 32543
  selector:
    name: gitlab-ce
  sessionAffinity: None
  type: NodePort
